[project]
name = "jamkit"
version = "0.1.0"
description = "Helpers for NI Raspberry Jam workshops"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
jamkit = [
    "jam_collector/assets/*.gif",
    "hack_the_robot/*.json",
    "hack_the_robot/data/*.txt",
]
